# Generated by Django 4.2.6 on 2023-10-24 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='webComunicados/img/logoEntidad/')),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=500)),
                ('detalle_corto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('S', 'Suspensión de actividades'), ('C', 'Suspensión de clase'), ('I', 'Información')], default='S', max_length=20)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webComunicados.entidad')),
            ],
        ),
    ]
