# Generated by Django 4.2.6 on 2023-10-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webComunicados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/webComunicados/img/logosEntidad/'),
        ),
    ]
